USERS_ENDPOINT = "https://random-data-api.com/api/v2/users"
API_CALLS_PER_MINUTE = 75

RETENTION_PERIOD_IN_DAYS = 30
LOG_GROUP = "DailyAIDataFetcher"
ERROR_LOG_STREAM = "Error"
STATUS_LOG_STREAM = "Status"
INFO_LOG_STREAM = "Info"

USERS_PER_API_CALL = (1, 150)
USERS_CALLS_PER_FETCH = (1, 100)
