USERS_ENDPOINT = "https://random-data-api.com/api/v2/users"
API_CALLS_PER_MINUTE = 15

RETENTION_PERIOD_IN_DAYS = 30
LOG_GROUP_NAME = "DailyAIDataFetcher"
ERROR_LOG_STREAM_NAME = "Error"
FETCHES_LOG_STREAM_NAME = "Fetch"
INFO_LOG_STREAM_NAME = "Info"

# USERS_PER_API_CALL = (1, 150)
USERS_PER_API_CALL = (1, 15)
# USERS_CALLS_PER_FETCH = (1, 100)
USERS_CALLS_PER_FETCH = (1, 3)
